// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package api

import (
	"proxy-pool/internal/core"
)

// Injectors from injector.go:

func NewApiServer() *Server {
	config := core.ProvideConfig()
	server := newApiServer(config)
	return server
}
