// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package proxy

import (
	"proxy-pool/internal/core"
	"proxy-pool/pkg/pool"
)

// Injectors from injector.go:

func NewProxy() *Proxy {
	config := core.ProvideConfig()
	client := core.ProvideRedis(config)
	repository := pool.NewRepository(client)
	checkerService := pool.NewCheckerService(client)
	fetcherJob := pool.NewFetcherJob(checkerService)
	service := pool.NewPoolService(repository, fetcherJob, checkerService)
	proxy := newProxy(config, service)
	return proxy
}
