// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package proxy

import (
	"proxy-pool/internal/core"
)

// Injectors from injector.go:

func NewProxy() *Proxy {
	config := core.ProvideConfig()
	proxy := newProxy(config)
	return proxy
}
